org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric 26.2
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.20
fabric_api_version=0.159.0+26.2
java_version=25

# Mod Properties
mod_version=2.10.1
maven_group=com.atemukesu.extendednoteblock
archives_base_name=extendednoteblock
publish.modrinth=JL9ooSG2
