package com.atemukesu.extendednoteblock.nbs.vanilla;

import com.atemukesu.extendednoteblock.nbs.vanilla.BlockStructure.BlockStateSpec;
import com.atemukesu.extendednoteblock.nbs.vanilla.BlockStructure.PlacedBlock;
import com.atemukesu.extendednoteblock.nbs.vanilla.BlockStructure.PlacedEntity;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.LinkedHashMap;
import java.util.Map;
import net.minecraft.SharedConstants;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.DoubleTag;
import net.minecraft.nbt.IntTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.NbtIo;

public final class StructureFileWriter {
    private StructureFileWriter() {
    }

    public static Path write(BlockStructure structure, Path requestedOutput, Format format,
            String name, String author) throws IOException {
        Path output = nextAvailablePath(requestedOutput);
        Files.createDirectories(output.getParent());
        CompoundTag root = format == Format.LITEMATIC
                ? createLitematic(structure, name, author)
                : createStructureNbt(structure);
        Path temporary = output.resolveSibling(output.getFileName() + ".tmp");
        NbtIo.writeCompressed(root, temporary);
        try {
            Files.move(temporary, output, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException ignored) {
            Files.move(temporary, output);
        }
        return output;
    }

    private static CompoundTag createLitematic(BlockStructure structure, String name, String author) {
        Palette palette = new Palette();
        int[] values = new int[structure.sizeX() * structure.sizeY() * structure.sizeZ()];
        ListTag tileEntities = new ListTag();
        for (PlacedBlock block : structure.blocks()) {
            int index = block.y() * structure.sizeX() * structure.sizeZ()
                    + block.z() * structure.sizeX() + block.x();
            values[index] = palette.id(block.state());
            if (block.blockEntity() != null) {
                CompoundTag tag = block.blockEntity().copy();
                tag.putInt("x", block.x());
                tag.putInt("y", block.y());
                tag.putInt("z", block.z());
                tileEntities.add(tag);
            }
        }

        ListTag entities = new ListTag();
        for (PlacedEntity entity : structure.entities()) {
            CompoundTag tag = entity.nbt().copy();
            tag.put("Pos", doubleList(entity.x(), entity.y(), entity.z()));
            entities.add(tag);
        }

        long now = System.currentTimeMillis();
        CompoundTag metadata = new CompoundTag();
        metadata.putString("Name", name);
        metadata.putString("Author", author == null || author.isBlank() ? "ExtendedNoteBlock" : author);
        metadata.putString("Description", "Vanilla music structure generated by ExtendedNoteBlock");
        metadata.putInt("RegionCount", 1);
        metadata.putInt("TotalVolume", values.length);
        metadata.putInt("TotalBlocks", structure.blocks().size());
        metadata.putLong("TimeCreated", now);
        metadata.putLong("TimeModified", now);
        metadata.put("EnclosingSize", positionTag(structure.sizeX(), structure.sizeY(), structure.sizeZ()));

        CompoundTag region = new CompoundTag();
        region.put("Position", positionTag(0, 0, 0));
        region.put("Size", positionTag(structure.sizeX(), structure.sizeY(), structure.sizeZ()));
        region.put("BlockStatePalette", palette.toNbt());
        region.putLongArray("BlockStates", pack(values, palette.size()));
        region.put("TileEntities", tileEntities);
        region.put("Entities", entities);
        region.put("PendingBlockTicks", new ListTag());
        region.put("PendingFluidTicks", new ListTag());

        CompoundTag regions = new CompoundTag();
        regions.put("Vanilla Music", region);
        CompoundTag root = new CompoundTag();
        root.putInt("MinecraftDataVersion", SharedConstants.WORLD_VERSION);
        root.putInt("Version", 7);
        root.putInt("SubVersion", 1);
        root.put("Metadata", metadata);
        root.put("Regions", regions);
        return root;
    }

    private static CompoundTag createStructureNbt(BlockStructure structure) {
        Palette palette = new Palette();
        structure.blocks().forEach(block -> palette.id(block.state()));

        ListTag blocks = new ListTag();
        for (PlacedBlock block : structure.blocks()) {
            CompoundTag entry = new CompoundTag();
            entry.putInt("state", palette.id(block.state()));
            entry.put("pos", intList(block.x(), block.y(), block.z()));
            if (block.blockEntity() != null) {
                entry.put("nbt", block.blockEntity().copy());
            }
            blocks.add(entry);
        }

        ListTag entities = new ListTag();
        for (PlacedEntity entity : structure.entities()) {
            CompoundTag entry = new CompoundTag();
            entry.put("pos", doubleList(entity.x(), entity.y(), entity.z()));
            entry.put("blockPos", intList((int) Math.floor(entity.x()), (int) Math.floor(entity.y()),
                    (int) Math.floor(entity.z())));
            entry.put("nbt", entity.nbt().copy());
            entities.add(entry);
        }

        CompoundTag root = new CompoundTag();
        root.putInt("DataVersion", SharedConstants.WORLD_VERSION);
        root.put("size", intList(structure.sizeX(), structure.sizeY(), structure.sizeZ()));
        root.put("palette", palette.toNbt());
        root.put("blocks", blocks);
        root.put("entities", entities);
        return root;
    }

    private static ListTag intList(int x, int y, int z) {
        ListTag list = new ListTag();
        list.add(IntTag.valueOf(x));
        list.add(IntTag.valueOf(y));
        list.add(IntTag.valueOf(z));
        return list;
    }

    private static ListTag doubleList(double x, double y, double z) {
        ListTag list = new ListTag();
        list.add(DoubleTag.valueOf(x));
        list.add(DoubleTag.valueOf(y));
        list.add(DoubleTag.valueOf(z));
        return list;
    }

    private static CompoundTag positionTag(int x, int y, int z) {
        CompoundTag tag = new CompoundTag();
        tag.putInt("x", x);
        tag.putInt("y", y);
        tag.putInt("z", z);
        return tag;
    }

    private static long[] pack(int[] values, int paletteSize) {
        int bits = Math.max(2, 32 - Integer.numberOfLeadingZeros(Math.max(1, paletteSize - 1)));
        long mask = (1L << bits) - 1L;
        long[] packed = new long[(int) ((((long) values.length * bits) + 63L) / 64L)];
        for (int index = 0; index < values.length; index++) {
            long bitIndex = (long) index * bits;
            int firstLong = (int) (bitIndex >>> 6);
            int bitOffset = (int) (bitIndex & 63L);
            long value = values[index] & mask;
            packed[firstLong] = (packed[firstLong] & ~(mask << bitOffset)) | (value << bitOffset);
            if (bitOffset + bits > 64) {
                int spill = 64 - bitOffset;
                packed[firstLong + 1] = (packed[firstLong + 1] >>> (bits - spill) << (bits - spill))
                        | (value >>> spill);
            }
        }
        return packed;
    }

    private static Path nextAvailablePath(Path requested) {
        if (!Files.exists(requested)) {
            return requested;
        }
        String fileName = requested.getFileName().toString();
        int dot = fileName.lastIndexOf('.');
        String base = dot > 0 ? fileName.substring(0, dot) : fileName;
        String extension = dot > 0 ? fileName.substring(dot) : "";
        for (int i = 2; i < 10_000; i++) {
            Path candidate = requested.resolveSibling(base + "-" + i + extension);
            if (!Files.exists(candidate)) {
                return candidate;
            }
        }
        return requested.resolveSibling(base + "-" + System.currentTimeMillis() + extension);
    }

    public enum Format {
        LITEMATIC(".litematic"),
        STRUCTURE_NBT(".nbt");

        private final String extension;

        Format(String extension) {
            this.extension = extension;
        }

        public String extension() {
            return extension;
        }

        public Format next() {
            return this == LITEMATIC ? STRUCTURE_NBT : LITEMATIC;
        }
    }

    private static final class Palette {
        private final Map<BlockStateSpec, Integer> ids = new LinkedHashMap<>();

        private Palette() {
            id(BlockStateSpec.of("minecraft:air"));
        }

        int id(BlockStateSpec state) {
            return ids.computeIfAbsent(state, ignored -> ids.size());
        }

        int size() {
            return ids.size();
        }

        ListTag toNbt() {
            ListTag list = new ListTag();
            ids.keySet().forEach(state -> {
                CompoundTag tag = new CompoundTag();
                tag.putString("Name", state.name());
                if (!state.properties().isEmpty()) {
                    CompoundTag properties = new CompoundTag();
                    state.properties().forEach(properties::putString);
                    tag.put("Properties", properties);
                }
                list.add(tag);
            });
            return list;
        }
    }
}
